/** ========== User management - Begin ========= */
// Register
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

// Login
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

// Logout
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

// Session
export const RESTORE_SESSION_REQUEST = "RESTORE_SESSION_REQUEST";
export const RESTORE_SESSION_SUCCESS = "RESTORE_SESSION_SUCCESS";
export const RESTORE_SESSION_FAILED = "RESTORE_SESSION_FAILED";
/** ========== User management - End ========= */
