export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";

export const LOAD_WEB3_SUCCESS = "LOAD_WEB3_SUCCESS";

// (risk) PROFILE
export const SET_RISK_PROFLE_SUCCESS = "SET_RISK_PROFLE_SUCCESS";
export const GET_RISK_PROFLE_SUCCESS = "GET_RISK_PROFLE_SUCCESS";

// USER MANAGEMENT
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

// USER MANAGEMENT - SAGAS
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
